// Generated by https://quicktype.io

export interface AlertaFiltrada {
  ok:     boolean;
  msg:    string;
  alerta: Alerta[];
}

export interface Alerta {
  id:        number;
  lat:       number;
  lng:       number;
  fecha:     string;
  hora:      string;
  ciudadano: number;
  Ciudadano: Ciudadano;
}

export interface Ciudadano {
  id:       number;
  dni:      string;
  nombre:   string;
  apellido: string;
  password: string;
  estado:   number;
}
