// Generated by https://quicktype.io

export interface ResultAlertas {
    ok:      boolean;
    msg:     string;
    results: Alerta[];
}

export interface Alerta {
    id:          number;
    descripcion: string;
    fecha:       string;
    hora:        string;
    lat:         number;
    lng:         number;
    tipo_alerta: string;
    img:         string;
    color:       string;
    ciudadano:   string;
    correo:      null | string;
    celular:     string;
    dni:         number;
    id_tipo:     number;
}
