// Generated by https://quicktype.io

export interface ResultFiltroDerivada {
  ok:             boolean;
  msg:            string;
  alertaDerivada: AlertaDerivada[];
}

export interface AlertaDerivada {
  id:         number;
  id_alerta:  number;
  id_usuario: number;
  atencion:   number;
  Alertum:    Alertum;
  Usuario:    Usuario;
}

export interface Alertum {
  id:         number;
  lat:        number;
  lng:        number;
  fecha:      string;
  hora:       string;
  ciudadano:  number;
  registrado: number;
  ano:        string;
  mes:        string;
  Ciudadano:  Usuario;
}

export interface Usuario {
  id:          number;
  dni:         string;
  nombre:      string;
  apellido:    string;
  password:    string;
  estado:      number;
  id_cargo?:   number;
  disponible?: number;
}
