// Generated by https://quicktype.io

export interface AlertaFiltrada {
  ok:     boolean;
  msg:    string;
  alerta: Alerta[];
}

export interface Alerta {
  id:         number;
  lat:        number;
  lng:        number;
  fecha:      string;
  hora:       string;
  ciudadano:  string;
  registrado: number;
  ano:        string;
  mes:        string;
  dni:        string;
  celular:    string;
  correo:     string;
  Ciudadano:  null;
}
