// Generated by https://quicktype.io

export interface ResultCentroAtenciones {
    ok:             boolean;
    msg:            string;
    centroAtencion: CentroAtencion[];
}
export interface ResultCentroAtencion {
    ok:             boolean;
    msg:            string;
    centroAtencion: CentroAtencion;
}
export interface CentroAtencion {
    id:               number;
    titulo:           string;
    lat:              string;
    lng:              string;
    direccion:        string;
    celular:          string;
    telefono:         string;
    id_tipo_atencion: number;
    id_usuario:       number;
    estado:           number;
    TipoAtencion:     TipoAtencion;
}

export interface TipoAtencion {
    id:     number;
    nombre: string;
    img:    string;
    estado: number;
}
