// Generated by https://quicktype.io

export interface ResultCiudadano {
    ok:        boolean;
    msg:       string;
    ciudadano: Ciudadano[];
}

export interface Ciudadano {
    id:       number;
    dni:      string;
    nombre:   string;
    apellido: string;
    password: string;
    estado:   number;
}
