// Generated by https://quicktype.io

export interface ResultControlPersonal {
  ok:   boolean;
  msg:  string;
  resp: Resp[];
}

export interface Resp {
  id:           number;
  id_usuario:   number;
  fechaingreso: string;
  horaingreso:  string;
  fechasalida:  null | string;
  horasalida:   null | string;
  Usuario:      Usuario;
}

export interface Usuario {
  id:         number;
  dni:        string;
  nombre:     string;
  apellido:   string;
  estado:     number;
  password:   string;
  id_cargo:   number;
  disponible: number;
  Cargo:      Cargo;
}

export interface Cargo {
  id:          number;
  cargo:       string;
  descripcion: string;
  estado:      number;
}
