// Generated by https://quicktype.io

export interface ResultGenerarCodigo {
  ok:        boolean;
  codigo:    string;
  ciudadano: Ciudadano;
}

export interface Ciudadano {
  id:       number;
  dni:      string;
  nombre:   string;
  apellido: string;
  password: string;
  estado:   number;
}
