// Generated by https://quicktype.io

export interface ResultLogin {
    ok:      boolean;
    msg:     string;
    usuario: Usuario;
    token:   string;
    id_control: number
}

export interface Usuario {
    id:       number;
    dni:      string;
    nombre:   string;
    apellido: string;
    estado:   number;
    password: string;
    id_cargo: number;
    cargousuario:    Cargo;
}

export interface Cargo {
    id:          number;
    cargo:       string;
    descripcion: string;
    estado:      number;
}
