// Generated by https://quicktype.io

export interface ResultOpcionFotos {
    ok:         boolean;
    msg:        string;
    opcionFoto: OpcionFoto[];
}
export interface ResultOpcionFoto {
    ok:         boolean;
    msg:        string;
    opcionFoto: OpcionFoto;
}


export interface OpcionFoto {
    id:     number;
    nombre: string;
}
