// Generated by https://quicktype.io

export interface ResultTipoAtenciones {
    ok:           boolean;
    msg:          string;
    tipoAtencion: TipoAtencion[];
}
export interface ResultTipoAtencion {
    ok:           boolean;
    msg:          string;
    tipoAtencion: TipoAtencion;
}


export interface TipoAtencion {
    id:     number;
    nombre: string;
    img:    string;
    estado: number;
}
