// Generated by https://quicktype.io

export interface ValidarSunat {
    ok:    boolean;
    msg:   string;
    datos: Datos;
}

export interface Datos {
    nombre:   string;
    apellido: string;
    dni:      string;
}
